name: Deploy React App to GitHub Pages

on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            # 1️⃣ Puxar o código do repo
            - name: Checkout repository
              uses: actions/checkout@v4

            # 2️⃣ Instalar Node.js
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 20  # ou a versão que usas localmente
                cache: "npm"

            # 3️⃣ Instalar dependências
            - name: Install dependencies
              run: npm ci

            # 4️⃣ Rodar build
            - name: Build React app
              run: npm run build
              env:
                VITE_API_KEY: ${{ secrets.VITE_API_KEY }}

            # 5️⃣ Deploy para GitHub Pages
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./dist
                # optional: configure branch if you want
                # publish_branch: gh-pages
